import {useEffect,useMemo,useState} from "react";
import {loadPokemonCatalog,type PokemonDexEntry} from "../services/ivCalculator";
import {BREEDING_GAINS,BREEDING_RULES,calculateBreeding} from "../services/breeding";import "./vplab.css";
const sprite=(n:number,shiny:boolean)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${shiny?"shiny/":""}${n}.png`;
const asset=(name:string)=>`/assets/vplab/breeding/${name}`;const q=(n:number)=>n.toFixed(3).replace(".",",");const num=(n:number)=>Math.round(n).toLocaleString("pt-BR");
export function BreedingPage(){
 const [catalog,setCatalog]=useState<PokemonDexEntry[]>([]),[slug,setSlug]=useState("charizard");
 const [qa,setQa]=useState(1.12),[qb,setQb]=useState(1.2),[iva,setIva]=useState(118),[ivb,setIvb]=useState(132);
 const [formA,setFormA]=useState<"normal"|"shiny">("normal"),[formB,setFormB]=useState<"normal"|"shiny">("normal");
 const [stones,setStones]=useState(true),[pheromone,setPheromone]=useState(false),[target,setTarget]=useState(1.5),[tier,setTier]=useState<"C"|"B"|"A">("C");
 useEffect(()=>{loadPokemonCatalog().then(setCatalog)},[]);const species=catalog.find(p=>p.s===slug)??catalog[5];
 const result=useMemo(()=>calculateBreeding({qa,qb,iva,ivb,formA,formB,stones,pheromone,target,shinyTier:tier}),[qa,qb,iva,ivb,formA,formB,stones,pheromone,target,tier]);
 return <main className="vplab-react"><div className="container">
 <header className="vplab-react__hero"><div><span className="vplab-react__eyebrow">Centro de Breeding · calculadora</span><h1>Simule o ovo antes de gastar os pais</h1><p>Coloque a Quality e o IV dos dois pais. O VPLab valida o par, mostra a distribuição real de ganho e projeta o filhote.</p></div></header>
 <div className="breed-v2-top"><section className="vplab-panel breed-react-input"><label>Espécie<select value={slug} onChange={e=>setSlug(e.target.value)}>{catalog.filter(p=>!p.boss).map(p=><option key={p.n} value={p.s}>{p.m}</option>)}</select></label><div className="breed-react-parents">{species&&<Parent label="Pai A" image={sprite(species.n,formA==="shiny")} quality={qa} setQuality={setQa} iv={iva} setIv={setIva} form={formA} setForm={setFormA}/>} {species&&<Parent label="Pai B" image={sprite(species.n,formB==="shiny")} quality={qb} setQuality={setQb} iv={ivb} setIv={setIvb} form={formB} setForm={setFormB}/>}</div>
 <div className="breed-react-options"><label><input type="checkbox" checked={pheromone} onChange={e=>setPheromone(e.target.checked)}/> Usar Strange Pheromone</label><label><input type="checkbox" checked={stones} onChange={e=>setStones(e.target.checked)}/> Dobrar Stones</label>{result.shinyPair&&<label>Tier Shiny<select value={tier} onChange={e=>setTier(e.target.value as "C"|"B"|"A")}><option>C</option><option>B</option><option>A</option></select></label>}<label>Quality alvo<input type="number" min=".8" max={result.shinyPair?undefined:2.6} step=".01" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label></div></section>
 <section className={`vplab-panel breed-react-compat ${result.compatible?"ok":"bad"}`}><h2>{result.reason}</h2><p>Diferença: {q(result.diff)} · IV herdado do Pai {result.bestIsA?"A":"B"}: {result.inheritedIv}/192.</p><h3>Filhote — distribuição de Quality</h3><div className="breed-react-outcomes">{result.outcomes.map(o=><article key={o.gain}><strong>+{q(o.gain)}</strong><span>{o.chance}%</span><small>{q(o.result)}</small></article>)}</div></section></div>
 <div className="breed-react-layout"><section className="vplab-panel"><h2>Distribuição do filhote</h2><p>Quality base: <b>{q(result.bestQ)}</b> · ganho esperado: <b>{q(result.expectedQuality-result.bestQ)}</b> · Quality esperada: <b>{q(result.expectedQuality)}</b></p><div className="breed-react-outcomes">{result.outcomes.map(o=><article key={o.gain}><strong>+{q(o.gain)}</strong><span>{o.chance}%</span><small>resultado {q(o.result)}</small></article>)}</div><div className="breed-react-iv"><b>IV esperado: {result.expectedIv.toFixed(2).replace(".",",")} / 192</b><small>{stones?(result.inheritedIv>=192?"IV total já está no máximo.":"5% de chance de +1 IV em um status aleatório abaixo de 32."):"Ative Dobrar Stones para a chance de melhoria."}</small></div></section>
 <section className="vplab-panel"><h2>Grátis × feromônio</h2><div className="breed-react-plans">{result.plans.map(plan=><article className={plan.key==="pheromone"?"gold":""} key={plan.key}><h3>{BREEDING_GAINS[plan.key].title}</h3><strong>{plan.eggs} ovos</strong><span>{num(plan.parents)} pais consumidos</span><span>$ {num(plan.gold)}</span><span>{num(plan.stones)} Stones</span>{plan.pheromones>0&&<span>{num(plan.pheromones)} feromônios</span>}</article>)}</div></section></div>
 <section className="vplab-panel breed-react-guide"><h2>Regras confirmadas</h2><div><article><strong>Nível {BREEDING_RULES.unlock}</strong><span>Desbloqueio do Centro</span></article><article><strong>$ {num(BREEDING_RULES.gold)}</strong><span>Custo base por ovo</span></article><article><strong>{BREEDING_RULES.stones}/{BREEDING_RULES.doubleStones}</strong><span>Stones normal/dobradas</span></article><article><strong>0,15</strong><span>Diferença máxima</span></article></div><figure><img src={asset("analise-dos-pais.webp")} alt="Tela de análise dos pais usada como referência para a projeção do Breeding" width="1068" height="589" loading="lazy"/><figcaption>Confira sempre a projeção exibida pelo jogo antes de consumir os pais.</figcaption></figure></section>
 </div></main>;
}
function Parent({label,image,quality,setQuality,iv,setIv,form,setForm}:{label:string;image:string;quality:number;setQuality:(n:number)=>void;iv:number;setIv:(n:number)=>void;form:"normal"|"shiny";setForm:(v:"normal"|"shiny")=>void}){return <article><img src={image} alt=""/><h2>{label}</h2><label>Quality<input type="number" min=".8" step=".01" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label><label>IV total<input type="number" min="0" max="192" value={iv} onChange={e=>setIv(Number(e.target.value))}/></label><label>Forma<select value={form} onChange={e=>setForm(e.target.value as "normal"|"shiny")}><option value="normal">Normal</option><option value="shiny">Shiny</option></select></label></article>}
