import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {Link,useSearchParams} from "react-router-dom";
import "./vplab.css";

type Stats={hp:number;atk:number;def:number;spAtk:number;spDef:number;speed:number};
type RankedPokemon={position:number|null;globalRank:number;tier:string;inRecommendedTeam:boolean;dexNo:number;name:string;types:string[];typesLabel:string;profile:string;score:number;bst:number;stats:Stats;offensiveCeilingR5:number;secondaryOffenseR5:number;robustnessR5:number;huntKanto:boolean;status:string;reading:string;whyBelowPrevious:string|null;source:string;exclusionReason?:string};
type Clan={id:string;name:string;elements:string;eligibleCount:number;usableCount:number;excludedCount:number;leader:string;leaderScore:number;recommendedTeam:string[];ranking:RankedPokemon[];excluded:RankedPokemon[]};
type ClanData={meta:{model:string;consolidatedAt:string;speciesAudited:number;usableSpecies:number;excludedSpecies:number;clanParticipations:number};methodology:{rank5Multiplier:number;bonusStats:string[];weights:Record<string,number>;premises:{label:string;text:string}[];limitations:string};clans:Record<string,Clan>};

const CLAN_ORDER=["volcanic","raibolt","orebound","naturia","gardestrike","ironhard","wingeon","psycraft","seavell","malefic"];
const COLORS:Record<string,string>={volcanic:"#ff6938",raibolt:"#f0c531",orebound:"#bc9b78",naturia:"#55c96d",gardestrike:"#d0623d",ironhard:"#91a6b3",wingeon:"#7fc9f6",psycraft:"#f15b96",seavell:"#58a9ff",malefic:"#9665dc"};
const sprite=(n:number)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${n}.png`;
const emblem=(id:string)=>`/vplab/legacy/assets/clans/${id}-symbol.png`;

export function ClanPage(){
 const [data,setData]=useState<ClanData|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState(""),[expanded,setExpanded]=useState(false);
 const [params,setParams]=useSearchParams();const clanId=CLAN_ORDER.includes(params.get("clan")??"")?params.get("clan")!:"volcanic";
 useEffect(()=>{fetch("/vplab-data/clan-ranking.json",{cache:"no-cache"}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json()}).then(setData).catch(()=>setError("Não foi possível carregar o ranking canônico."))},[]);
 const clan=data?.clans[clanId];const substitutes=useMemo(()=>clan?.ranking.slice(6).filter(p=>(!query||p.name.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))&&(!type||p.types.includes(type)))??[],[clan,query,type]);
 const selectClan=(id:string)=>{setParams({clan:id});setExpanded(false);setQuery("");setType("")};
 return <main className="vplab-react clan-react" style={{"--clan":COLORS[clanId]} as CSSProperties}><div className="container">
  <nav className="vplab-react__tools"><Link to="/vplab/">Avaliar IV</Link><Link to="/vplab/pokedex">Pokédex</Link><Link to="/vplab/pokefipe">PokeFipe</Link><Link to="/vplab/rota">Rota de caça</Link><Link to="/vplab/breeding">Breeding</Link><Link className="is-active" to="/vplab/clas">Clãs</Link><a href="/vplab/legacy/?tab=profissoes">Profissões</a></nav>
  <header className="vplab-react__hero"><div><span className="vplab-react__eyebrow">Ranking canônico · Rank 5</span><h1>Clãs e times recomendados</h1><p>Escolha um clã para consultar o Top 6 oficial, substitutos e critérios da auditoria.</p></div>{data&&<span className="vplab-react__privacy">Consolidado em {data.meta.consolidatedAt}</span>}</header>
  {error&&<section className="vplab-panel clan-react-error">{error}</section>}
  {!data&&!error&&<section className="vplab-panel clan-react-loading">Carregando os 10 clãs…</section>}
  {data&&<><section className="clan-react-picker" aria-label="Escolha um clã">{CLAN_ORDER.map(id=>{const item=data.clans[id];return <button key={id} className={id===clanId?"is-active":""} onClick={()=>selectClan(id)}><img src={emblem(id)} alt=""/><span>{item.name}<small>{item.elements}</small></span></button>})}</section>
  {clan&&<><section className="vplab-panel clan-react-heading"><img src={emblem(clan.id)} alt={`Emblema ${clan.name}`}/><div><span>{clan.elements}</span><h2>{clan.name}</h2><p>Líder do ranking: <b>{clan.leader}</b> · score {clan.leaderScore.toFixed(2).replace(".",",")}</p></div><div><strong>{clan.usableCount}</strong><small>utilizáveis</small><strong>{clan.excludedCount}</strong><small>excluídos</small></div></section>
  <section className="vplab-panel clan-react-roster"><header><div><span>Equipe recomendada</span><h2>Top 6 do {clan.name}</h2></div><small>Ordem preservada da base canônica</small></header><div className="clan-react-grid">{clan.ranking.slice(0,6).map(p=><PokemonCard key={p.dexNo} pokemon={p}/>)}</div></section>
  {clan.ranking.length>6&&<section className="vplab-panel clan-react-subs"><header><div><span>Outras opções</span><h2>{clan.ranking.length-6} substitutos</h2></div><button onClick={()=>setExpanded(v=>!v)}>{expanded?"Recolher":"Ver todos"}</button></header>{expanded?<><div className="clan-react-filters"><input aria-label="Buscar substituto" placeholder="Buscar Pokémon" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar por tipo" value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option>{[...new Set(clan.ranking.slice(6).flatMap(p=>p.types))].map(t=><option key={t}>{t}</option>)}</select></div><div className="clan-react-subgrid">{substitutes.map(p=><PokemonCard key={p.dexNo} pokemon={p}/>)}</div>{!substitutes.length&&<p>Nenhum substituto corresponde ao filtro.</p>}</>:<div className="clan-react-preview">{clan.ranking.slice(6,9).map(p=><PokemonCard key={p.dexNo} pokemon={p}/>)}</div>}</section>}
  {!!clan.excluded.length&&<details className="vplab-panel clan-react-details"><summary>{clan.excluded.length} espécies auditadas e excluídas</summary><div>{clan.excluded.map(p=><article key={p.dexNo}><img src={sprite(p.dexNo)} alt=""/><span><b>{p.name}</b><small>{p.exclusionReason}</small></span></article>)}</div></details>}
  <details className="vplab-panel clan-react-details"><summary>Como o ranking foi calculado</summary><div className="clan-react-method"><p>Rank 5 aplica <b>×{data.methodology.rank5Multiplier}</b> em {data.methodology.bonusStats.join(", ")}. O ranking privilegia teto ofensivo ({data.methodology.weights.offensiveCeiling*100}%), robustez e velocidade.</p>{data.methodology.premises.map(p=><article key={p.label}><b>{p.label}</b><span>{p.text}</span></article>)}<p>{data.methodology.limitations}</p></div></details>
  <section className="clan-react-audit"><span><b>{data.meta.speciesAudited}</b> espécies auditadas</span><span><b>{data.meta.usableSpecies}</b> utilizáveis</span><span><b>{data.meta.excludedSpecies}</b> excluídas</span><span><b>{data.meta.clanParticipations}</b> participações em clãs</span></section></>}</>}</div></main>
}

function PokemonCard({pokemon:p}:{pokemon:RankedPokemon}){return <article className="clan-react-card"><i>#{p.position}</i><img src={sprite(p.dexNo)} alt=""/><div><span>Tier {p.tier}</span><h3>{p.name}</h3><small>{p.typesLabel} · {p.profile}</small><b>{p.score.toFixed(2).replace(".",",")} pts</b></div><details><summary>Detalhes</summary><p>{p.reading}</p><small>HP {p.stats.hp} · ATK {p.stats.atk} · DEF {p.stats.def} · SpA {p.stats.spAtk} · SpD {p.stats.spDef} · SPD {p.stats.speed}</small>{p.whyBelowPrevious&&<p>{p.whyBelowPrevious}</p>}<a href={p.source} target="_blank" rel="noreferrer">Fonte oficial</a></details></article>}
