import "./vplab.css";

const ASSET="/assets/vplab/professions/official/";
const ranks=[
 {rank:"E",title:"Aprendiz",bonus:"+3%",multiplier:"×1,03",next:"D",species:50,photos:20,defeats:"—"},
 {rank:"D",title:"Aventureiro",bonus:"+6%",multiplier:"×1,06",next:"C",species:100,photos:50,defeats:"200"},
 {rank:"C",title:"Especialista",bonus:"+9%",multiplier:"×1,09",next:"B",species:200,photos:150,defeats:"500"},
 {rank:"B",title:"Elite",bonus:"+12%",multiplier:"×1,12",next:"A",species:300,photos:300,defeats:"1.000"},
 {rank:"A",title:"Campeão",bonus:"+15%",multiplier:"×1,15",next:"S",species:450,photos:600,defeats:"2.000"},
 {rank:"S",title:"Mestre Pokémon",bonus:"+18%",multiplier:"×1,18",next:null,species:null,photos:null,defeats:null}
];
const talents=[["water","Água"],["fire","Fogo"],["grass","Planta"],["electric","Elétrico"],["fighting","Lutador"],["flying","Voador"],["ghost","Fantasma"],["psychic","Psíquico"],["ground","Terra"],["steel","Aço"]];
const upcoming=[["icon_botanist.png","Botânico"],["icon_scientist.png","Cientista"],["icon_researcher.png","Pesquisador Pokémon"]];
const icon=(file:string)=>`${ASSET}${file}`;

export function ProfessionsPage(){return <main className="vplab-react prof-react"><div className="container">
 <header className="prof-react-hero"><img src={icon("header_prestige.png")} alt="Treinadores fotografando Pokémon no banner oficial das Profissões" width="1792" height="594"/><div><span className="vplab-react__eyebrow">Sistema de profissões</span><h1>Especializações do treinador</h1><p>Profissões oferecem mecânicas próprias e progressão por ranks. No momento, apenas o Treinador de Prestígio está disponível no jogo.</p></div><aside><b>1 profissão ativa</b><span>Outras três e a árvore de talentos seguem em desenvolvimento.</span></aside></header>
 <section className="vplab-panel prof-react-active" aria-labelledby="prestige-title"><header><img src={icon("icon_prestige.png")} alt=""/><div><span>Disponível no jogo</span><h2 id="prestige-title">Treinador de Prestígio</h2><p>Uma carreira para quem caça Pokémon raros. Ela recompensa encontros com shinies e aumenta diretamente sua chance de captura conforme o rank avança.</p></div></header><div className="prof-react-mechanics"><article><img src={icon("rare_pokemon_picture.png")} alt="Rare Pokémon Picture"/><div><h3>Fotografia de shinies</h3><p>Quando um Shiny aparece na sua hunt, você recebe automaticamente <b>1 Rare Pokémon Picture</b>. Não é necessário capturá-lo.</p></div></article><article><strong>+3%</strong><div><h3>Bônus de captura</h3><p>Cada rank acrescenta 3% ao multiplicador: começa em <b>+3% no rank E</b> e chega a <b>+18% no rank S</b>.</p></div></article></div></section>
 <section className="vplab-panel prof-react-section" aria-labelledby="ranks-title"><span className="vplab-react__eyebrow">Progressão</span><h2 id="ranks-title">Ranks e bônus de captura</h2><p>O bônus é cumulativo e acompanha o rank atual da profissão.</p><ol className="prof-react-ranks">{ranks.map((r,i)=><li className={r.rank==="S"?"is-final":""} key={r.rank}><small>{String(i+1).padStart(2,"0")}</small><b>{r.rank}</b><span>{r.title}</span><strong>{r.bonus}</strong><em>{r.multiplier}</em></li>)}</ol></section>
 <section className="vplab-panel prof-react-section" aria-labelledby="requirements-title"><span className="vplab-react__eyebrow">O que falta para evoluir</span><h2 id="requirements-title">Requisitos de cada rank</h2><p>Todas as metas da linha precisam ser cumpridas juntas.</p><div className="prof-react-table" tabIndex={0} role="region" aria-labelledby="requirements-title"><table><caption className="sr-only">Requisitos para avançar entre os ranks do Treinador de Prestígio</caption><thead><tr><th scope="col">Evolução</th><th scope="col">Espécies diferentes</th><th scope="col">Rare Pokémon Pictures</th><th scope="col">Derrotas por tipo</th></tr></thead><tbody>{ranks.filter(r=>r.next).map(r=><tr key={r.rank}><th scope="row">{r.rank} → {r.next}</th><td>{r.species}</td><td>{r.photos}</td><td>{r.defeats}</td></tr>)}</tbody></table></div><small className="prof-react-swipe">Deslize a tabela para ver todas as colunas.</small><div className="prof-react-legend"><article><h3>Espécies</h3><p>Espécies diferentes registradas por captura.</p></article><article><h3>Rare Pokémon Picture</h3><p>Item recebido ao encontrar um Shiny e consumido na evolução.</p></article><article><h3>Derrotas por tipo</h3><p>Abates exigidos de cada tipo. E → D não pede derrotas.</p></article></div></section>
 <section className="vplab-panel prof-react-talents" aria-labelledby="talents-title"><span className="vplab-react__eyebrow">Talentos do treinador</span><h2 id="talents-title">Árvore de talentos ainda não disponível</h2><p>O sistema é anunciado no jogo, mas ainda não está ativo: pontos, caminhos e efeitos ainda estão em desenvolvimento. Esta seção será atualizada quando a árvore estiver disponível.</p><div>{talents.map(([file,label])=><span key={file}><img src={icon(`talent_${file}.png`)} alt=""/><b>{label}</b></span>)}</div></section>
 <section className="vplab-panel prof-react-section" aria-labelledby="upcoming-title"><span className="vplab-react__eyebrow">Ainda não jogáveis</span><h2 id="upcoming-title">Outras profissões</h2><p>Anunciadas no jogo, sem mecânicas ou requisitos publicados até agora.</p><ul className="prof-react-upcoming">{upcoming.map(([file,name])=><li key={file}><img src={icon(file)} alt=""/><span><h3>{name}</h3><p>Em desenvolvimento</p></span></li>)}</ul></section>
 </div></main>}
